# Basic HP
tag:
  desc: wandb tags
  value:
    - Debug
model_type:
  desc: which model to use (CNN/TCN/MLP/RNN)
  value: MLP
epochs:
  desc: Number of epochs to train over
  value: 300
batch_size:
  desc: Size of each mini-batch
  value: 16384
momentum:
  desc: momentum for SGD
  value: 0.9
optim:
  desc: optimizer to use
  value: SGD
n_features:
  desc: number of features to include (max 40)
  value: 40

# Learning rate
learning_rate:
  desc: initial learning rate
  value: 0.00001
lr_scheduler:
  desc: if scheduler is on
  value: False
lr_finder:
  desc: is lr finder should run
  value: True
log_lr:
  desc: log lr finder to wandb
  value: False
min_lr:
  desc: minimum lr for CLR
  value: 0.00001
max_lr:
  desc: cyclic lr max value
  value: 0.2
lr_metric:
  desc: Loss or TSS (loss is better)
  value: Loss


# TCN HP
levels:
  desc: num of tcn blocks
  value: 2
ksize:
  desc: kernel size (smallest is 2)
  value: 3
nhid:
  desc: number of filters
  value: 80
seq_len:
  desc: size of sequence (Be 1 for MLP)
  value: 1

# MLP
layers:
  desc: MLP layers
  value: 2
hidden_units:
  desc: number hidden nodes in layer
  value: 500

# Regularizer
dropout:
  desc: dropout applied to layers
  value: 0.0
weight_decay:
  desc: L2 regularizing
  value: 0.0

# Cross Validation
liu_fold:
  desc: If liu fold should be done
  value: False
cross_validation:
  desc: if crossval should be performed
  value: False
nested_cv:
  desc: if nested crossval should be performed
  value: False
n_splits:
  desc: number of splits
  value: 3

# Environment
skorch:
  desc: if skorch should be used to train (Faster, fewer metrics)
  value: True
flare_label:
  desc: Types of flare class
  value: M5
seed:
  desc: random seed
  value: 49
clip:
  desc: gradient clipping value (not skorch)
  value: -1
cuda:
  desc: enables cuda training
  value: True
early_stop:
  desc: stops training if overfitting
  value: False
patience:
  desc: amount of epochs for early stopping
  value: 30
training:
  desc: Trains models, else only tests
  value: True
model_name:
  dsec: The model used for evaluation (if training disabled, 1_100_8192_1e-3)
  value: dewald123/liu_pytorch_MLP/ogkzvcf0
num_workers:
  desc: number of gpu workers
  value: 9
parse_args:
  desc: if args should be parse for bash script
  value: False

# Dataset
dataset:
  desc: which dataset to use (Liu/Liu_train/Liu_z/Liu_transformed/Krynauw)
  value: Liu_train

# Interpretation
interpret:
  desc: activate captum/SHAP attribution methods
  value: False

