# Basic HP
tag:
  desc: wandb tags
  value:
    - Debug
model_type:
  desc: which model to use (CNN/TCN/MLP/RNN)
  value: TCN
epochs:
  desc: Number of epochs to train over
  value: 14
batch_size:
  desc: Size of each mini-batch
  value: 65536
learning_rate:
  desc: initial learning rate
  value: 0.01
momentum:
  desc: momentum for SGD
  value: 0.9
optim:
  desc: optimizer to use
  value: Adam
lr_scheduler:
  desc: if scheduler is on
  value: True
max_lr:
  desc: cyclic lr max value
  value: 0.1
n_features:
  desc: number of features to include (max 40)
  value: 40

# TCN HP
levels:
  desc: num of tcn blocks
  value: 1
ksize:
  desc: kernel size (smallest is 2)
  value: 2
nhid:
  desc: number of filters
  value: 40
seq_len:
  desc: size of sequence (Be 1 for MLP)
  value: 1

# MLP
layers:
  desc: MLP layers
  value: 2
hidden_units:
  desc: number hidden nodes in layer
  value: 200

# Regularizer
dropout:
  desc: dropout applied to layers
  value: 0.4
weight_decay:
  desc: L2 regularizing
  value: 0.0

# Cross Validation
cross_validation:
  desc: if crossval should be performed
  value: False
nested_cv:
  desc: if nested crossval should be performed
  value: True
n_splits:
  desc: number of splits
  value: 3

# Environment
skorch:
  desc: if skorch should be used to train (Faster, fewer metrics)
  value: True
flare_label:
  desc: Types of flare class
  value: M5
seed:
  desc: random seed
  value: 20
clip:
  desc: gradient clipping value (not skorch)
  value: -1
cuda:
  desc: enables cuda training
  value: True
early_stop:
  desc: stops training if overfitting
  value: True
patience:
  desc: amount of epochs for early stopping
  value: 30
training:
  desc: Trains models, else only tests
  value: True
model_name:
  dsec: The model used for evaluation (if training disabled, 1_100_8192_1e-3)
  value: dewald123/liu_pytorch_MLP/ogkzvcf0
num_workers:
  desc: number of gpu workers
  value: 9
parse_args:
  desc: if args should be parse for bash script
  value: False

# Dataset
dataset:
  desc: which dataset to use (Liu/Krynauw)
  value: Liu

# Interpretation
interpret:
  desc: activate captum/SHAP attribution methods
  value: False


