# Basic HP
tag:
  desc: wandb tags
  value:
    - Skorch
    - Liu_Fold
    - BatchNorm
    - Debug
model_type:
  desc: which model to use (TCN/MLP)
  value: MLP
epochs:
  desc: Number of epochs to train over
  value: 600
batch_size:
  desc: Size of each mini-batch
  value: 512
learning_rate:
  desc: initial learning rate
  value: 0.001
optim:
  desc: optimizer to use
  value: Adam
n_features:
  desc: number of features to include (max 40)
  value: 40

# TCN HP
levels:
  desc: num of tcn blocks
  value: 1
ksize:
  desc: kernel size (smallest is 2)
  value: 2
nhid:
  desc: number of filters
  value: 40
seq_len:
  desc: size of sequence (Be 1 for MLP)
  value: 1

# MLP
layers:
  desc: MLP layers
  value: 1
hidden_units:
  desc: number hidden nodes in layer
  value: 100

# Regularizer
dropout:
  desc: dropout applied to layers
  value: 0.0
weight_decay:
  desc: L2 regularizing
  value: 0.0

# Cross Validation
cross_validation:
  desc: if crossval should be performed
  value: False
n_splits:
  desc: number of splits
  value: 5

# Environment
skorch:
  desc: if skorch should be used to train (Faster, fewer metrics)
  value: True
flare_label:
  desc: Types of flare class
  value: M5
seed:
  desc: random seed
  value: 46
cuda:
  desc: enables cuda training
  value: True
early_stop:
  desc: stops training if overfitting
  value: True
training:
  desc: Trains models, else only tests
  value: True
num_workers:
  desc: number of gpu workers
  value: 9
patience:
  desc: amount of epochs for early stopping
  value: 10


