FROM continuumio/miniconda3

WORKDIR /app

# Create the environment:
COPY deepflarepred.yml .
RUN conda env create -f deepflarepred.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "DeepFlarePred", "/bin/bash", "-c"]

# Make sure the environment is activated:
RUN echo "Make sure flask is installed:"
#RUN python -c "import flask"

# The code to run when container is started:
COPY main_TCN_Liu.py .
ENTRYPOINT ["conda", "run", "-n", "DeepFlarePred", "python", "main_TCN_Liu.py"]